import pyautogui
def youtube(id):
    pyautogui.hotkey("win")
    s(1)
    pyautogui.write("Google")
    s(0.1)
    pyautogui.hotkey("enter")
    s(2)
    pyautogui.write("youtube.com")
    pyautogui.keyDown("shift")
    pyautogui.hotkey("7")
    pyautogui.keyUp("shift")
    pyautogui.write("watch?v")
    pyautogui.keyDown("shift")
    pyautogui.hotkey("0")
    pyautogui.keyUp("shift")
    pyautogui.write(id)
    s(2)
    pyautogui.hotkey("enter")
    s(3)
    pyautogui.hotkey("f")
